name: Build mod-yla with LuaJIT 🌙

on:
  push:
    branches: [master-shadows]
  pull_request:

jobs:
  build_luajit:
    uses: ./.github/workflows/core-build-base.yml
    with:
      lua_version: 'luajit'
